#!/usr/bin/env python3
class Dog(object):
    def __init__(self,name,age):
        self._name=name
        self._age=age
    def get_name(self):
        return self._name.lower().capitalize()
    def get_age(self):
        return self._age
    def set_name(self,value):
        self._name=value
    def bark(self):
        print(self.get_name()+' is wangwang '+self.get_age())

dog=Dog('liuQQQQQqin','10')
dog.bark()
