#!/usr/bin/env python3

class Animal:
    @property
    def age(self):
        return self._age
    @age.setter
    def age(self,value):
        if isinstance(value,int):
            self._age=value
        else:
            raise valueError

cat=Animal()
cat.age=10
print(cat.age)

cat.age='aaa'
print(cat.age)

